name: Run Selenium UI Tests

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        pip install selenium pytest

# May need to change the main.py
    - name: Start Flask App (Background)
      run: |
        nohup python main.py & sleep 3


    - name: Run Selenium Tests
      run: pytest tests/test_ui.py
